version: '3.8'

services:
  # Main application service
  scheve-schilder-gallery:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: scheve-schilder-gallery
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - gallery-network
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional - for development with hot reload)
  scheve-schilder-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: scheve-schilder-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - gallery-network
    profiles:
      - dev

networks:
  gallery-network:
    driver: bridge

# Optional: Add volume for persistent data if needed
volumes:
  gallery-data:
